# Generated by Django 4.2 on 2025-04-04 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=244)),
                ('apellido', models.CharField(max_length=244)),
                ('telefono', models.CharField(max_length=10)),
                ('tipoDocumento', models.IntegerField(choices=[(1, 'TI'), (2, 'CC'), (3, 'CE'), (4, 'PA')], default=1)),
                ('numeroDocumento', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=244)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(help_text='AAAA-MM-DD')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=244)),
                ('apellido', models.CharField(max_length=244)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('director', 'Director de Evento')], default='cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('tipoDocumento', models.IntegerField(choices=[(1, 'TI'), (2, 'CC'), (3, 'CE'), (4, 'PA')], default=1)),
                ('numeroDocumento', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=244, unique=True)),
                ('informacion', models.TextField()),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(max_length=244)),
                ('requisito', models.TextField()),
                ('comision', models.DecimalField(decimal_places=2, default=0.1, max_digits=3)),
                ('imagen', models.ImageField(default='default.jpg', upload_to='imagen_servicios/')),
                ('direccion', models.CharField(default='agregar direccion', max_length=244)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible')], default='disponible', max_length=20)),
                ('fecha', models.DateField(default='2025-04-03', help_text='AAAA-MM-DD')),
                ('cupo_maximo', models.IntegerField(default=30)),
                ('cupos_vendidos', models.IntegerField(default=0)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk6_servicio_Cliente', to='fullcrazy.cliente')),
                ('idMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk7_servicio_municipio', to='fullcrazy.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPeticion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(help_text='AAAA-MM-DD')),
                ('descripcion', models.TextField()),
                ('valor', models.IntegerField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk8_peticion_cliente', to='fullcrazy.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='AAAA-MM-DD')),
                ('total', models.IntegerField()),
                ('metodoPago', models.IntegerField(choices=[(1, 'Tarjeta de Credito'), (2, 'Tarjeta de Debito')], default=1)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk11_facturas_cliente', to='fullcrazy.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioUnitario', models.IntegerField()),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk10_detalleFactura_factura', to='fullcrazy.factura')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk9_detalleFactura_servicio', to='fullcrazy.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioUnitario', models.IntegerField()),
                ('idCarrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk3_detalleCarrito_carrito', to='fullcrazy.carrito')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk2_detalleCarrito_servicio', to='fullcrazy.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAdministrador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk5_detalleAdministrador_administrador', to='fullcrazy.administrador')),
                ('idPeticion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk4_detalleAdministrador_peticion', to='fullcrazy.peticion')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk1_Carrito_cliente', to='fullcrazy.cliente'),
        ),
    ]
