# Generated by Django 4.0.6 on 2025-04-04 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0002_alter_servicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 4, 4), help_text='AAAA-MM-DD'),
        ),
    ]
