# Generated by Django 4.0.6 on 2025-04-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0003_alter_servicio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateField(help_text='AAAA-MM-DD'),
        ),
    ]
