# Generated by Django 4.0.6 on 2025-04-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0004_alter_servicio_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='idCliente',
        ),
        migrations.RemoveField(
            model_name='detalleadministrador',
            name='idAdministrador',
        ),
        migrations.RemoveField(
            model_name='detalleadministrador',
            name='idPeticion',
        ),
        migrations.RemoveField(
            model_name='detallecarrito',
            name='idCarrito',
        ),
        migrations.RemoveField(
            model_name='detallecarrito',
            name='idServicio',
        ),
        migrations.RemoveField(
            model_name='peticion',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('director', 'Director de Evento'), ('administrador', 'Administrador')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk4_detalleFactura_factura', to='fullcrazy.factura'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk3_detalleFactura_servicio', to='fullcrazy.servicio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='f5_facturas_cliente', to='fullcrazy.cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk1_servicio_cliente', to='fullcrazy.cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='idMunicipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk2_servicio_municipio', to='fullcrazy.municipio'),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='DetalleAdministrador',
        ),
        migrations.DeleteModel(
            name='DetalleCarrito',
        ),
        migrations.DeleteModel(
            name='Peticion',
        ),
    ]
