# Generated by Django 4.0.6 on 2025-04-04 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0006_alter_servicio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today, help_text='AAAA-MM-DD'),
        ),
    ]
