# Generated by Django 4.2 on 2025-04-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0013_remove_carrito_idcliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
