# Generated by Django 4.2 on 2025-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0014_alter_servicio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='subtotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
