# Generated by Django 4.2.1 on 2025-04-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0015_detallefactura_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='idMunicipio',
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk3_detalleFactura_factura', to='fullcrazy.factura'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk2_detalleFactura_servicio', to='fullcrazy.servicio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk4_facturas_cliente', to='fullcrazy.cliente'),
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
