# Generated by Django 4.2 on 2025-04-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0016_remove_servicio_idmunicipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='precioComision',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
