# Generated by Django 4.2 on 2025-04-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0017_detallefactura_preciocomision'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='totalNoComision',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
