# Generated by Django 4.2 on 2025-04-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcrazy', '0018_detallefactura_totalnocomision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=244),
        ),
    ]
